### ISSUE TITLE
Kyoukai prints 404 to console when a 200 is sent in errorhandler

### ISSUE THREAD

**Issue by martmists** [SunDwarf/Kyoukai#11]
Pls fix

```
@app.errorhandler(404)
async def handle_404(ctx, exc):
    try:
        resp = open(ctx.request.path).read()
        resp = Response(200, resp)
    except Exception:
        resp = Response(404, "404")
    return resp
```

**Comment by ccubed** [comment]
This is not an error. There is never a case where a server should decide to send a 404 and then resolve a 404 into a 200. That's not how the specification works.

**Comment by martmists** [comment]
So how do you suggest I add functionality like this whenever a page isn't
found in the routes defined by the code?

**Comment by ccubed** [comment]
You should either return a '404 page' like most sites or just return the 404 with no content and let the web browser give its own default not found page.

**Comment by SunDwarf** [comment]
The logging call is before the error handler is hit.

If you want to do weird stuff like this, use a custom router, with the other changes in 1.10.

**Comment by martmists** [comment]
What I'm saying is that I want kyoukai to look if a file exists, and only
404 if even the file isn't found. I might get a lot of pages and I'm not
gonna add routes to all of them (even regex would be too much)

**Comment by ccubed** [comment]
That is not how a web server (or hell, even a file server) works. Thank you, please come again once you understand how these things work.

**Comment by SunDwarf** [comment]
You can literally make a catch-all route with `/(.*)`. It will catch ANY request not caught by other requests, as long as you define it LAST in the order.
