### ISSUE TITLE
Request has no attribute 'source'

### ISSUE THREAD

**Issue by martmists** [SunDwarf/Kyoukai#13]
<img src="https://b.catgirlsare.sexy/LCQ-.png"/>
This is from the docs, yet my console reports
`AttributeError: 'Request' object has no attribute 'source'`

using latest version of Kyoukai from git fyi

**Comment by SunDwarf** [comment]
This should be corrected within 2.0 (with whatever the new property on the Werkzeug request is) on the uWSGI worker by default - I'll make sure to add that to the default `httptools` worker tonight.
