### ISSUE TITLE
CONTENT_LENGTH_MISMATCH when using a big response

### ISSUE THREAD

**Issue by martmists** [SunDwarf/Kyoukai#21]
I have noticed that, when using big responses, I often get a CONTENT_LENGTH_MISMATCH, and I have to refresh multiple times to make it work. Now I do realise that my responses are way too big, but otherwise I'd have to make a couple hundred requests to my server to get all 7M characters (More specifically: `Content-Length:7234358`) used in the response. I'm not sure if this is an issue with Kyoukai or Chrome, but I've had bigger responses on other websites which I remember worked just fine, hence the issue on this repo.

**Comment by SunDwarf** [comment]
whoops

**Comment by martmists** [comment]
gj fuyu

**Comment by SunDwarf** [comment]
I need code that I can use to reproduce this, please.

**Comment by martmists** [comment]
iirc you fixed this, so I'm closing the issue.
