### ISSUE TITLE
Lock url mapping to only one request per time

### ISSUE THREAD

**Issue by AlbertoOS** [SunDwarf/Kyoukai#24]
Is there a way in Kyoukai to lock a route to only process one request at a time or even using something already in the language?

For example:
```python
@app.route('/status')
async def index(ctx):
    if status_lock.acquire(False):
        # do long operations here
        return json.dumps({'message': 'Complete'})
    else:
        return json.dumps({'message': 'A request on status is already running'})
```

**Comment by SunDwarf** [comment]
You can use an [asyncio Lock](https://docs.python.org/3/library/asyncio-sync.html#asyncio.Lock).
