### ISSUE TITLE
No documentation on `debug` attribute of application object

### ISSUE THREAD

**Issue by mplanchard** [SunDwarf/Kyoukai#4]
I started using Kyoukai for a side-project to help me better understand asynchronous programming in Python. I've been working on a fork with small changes to the documentation, but this one required a bit more input.

The `debug` attribute of an application object seems to do two things:

* show a formatted traceback if a 500 is received
* create a response object formatted by the `_debugger`, which defaults to the `Kyoukai Debugger` class *if* `__debugger__ = 'yes'` is in the `ctx.request` args.

Is that correct? Is there more to it?

I'll be continuing to play around with this and am happy to include what I learn in my eventual documentation PR if desired. It would also be nice to know what the intended use case and/or application flow is for this, though.

Thanks!

**Comment by SunDwarf** [comment]
Yes, this is pretty much what the debug attribute does. It's very similar to setting `debug=True` in a Flask application; it loads the Werkzeug debugger (which I wrote a thin wrapper around to get it to work in a non-WSGI environment) and allows you to use that to debug issues in the webapp.

**Comment by mplanchard** [comment]
Awesome. Thanks for the framework! It's been fun to learn so far.
