### ISSUE TITLE
share objects in a blueprint

### ISSUE THREAD

**Issue by njordr** [SunDwarf/Kyoukai#9]
Hi.

Is there a way to share an object (let say for example a dict) in a blueprint?

I've a before request fuction that validate a token. I'm wandering if a I can create a dict with all the valid tokens and launch the validate function passing the dict to it

**Comment by SunDwarf** [comment]
Well, you can just monkeypatch the item onto the Blueprint, ala `bp.whatever = {"my": "dict}`.

I suppose there could be a use-case for per blueprint configuration.

**Comment by njordr** [comment]
Thanks, it works
